export type icons =
  'custom-inherited-disabled' |
  'custom-inherited' |
  'custom-uninherited' |
  'default-action-bookmark' |
  'default-action-bulk-edit' |
  'default-action-circle-download' |
  'default-action-circle-upload' |
  'default-action-cloud-download' |
  'default-action-cloud-upload' |
  'default-action-document-view' |
  'default-action-drag-horizontal' |
  'default-action-drag-vertical' |
  'default-action-duplicate' |
  'default-action-external' |
  'default-action-filter' |
  'default-action-grab' |
  'default-action-history' |
  'default-action-log-in' |
  'default-action-log-out' |
  'default-action-moon' |
  'default-action-more-horizontal' |
  'default-action-more-vertical' |
  'default-action-move-file' |
  'default-action-preview' |
  'default-action-quickjump' |
  'default-action-replace' |
  'default-action-save' |
  'default-action-screen-full' |
  'default-action-screen-minimize' |
  'default-action-search' |
  'default-action-settings' |
  'default-action-share' |
  'default-action-sliders' |
  'default-action-sort-down' |
  'default-action-sort-up' |
  'default-action-sun' |
  'default-action-tags' |
  'default-action-thumb-down' |
  'default-action-thumb-up' |
  'default-action-trash' |
  'default-action-tray-down' |
  'default-action-tray-up' |
  'default-arrow-360-full' |
  'default-arrow-360-left' |
  'default-arrow-360-right' |
  'default-arrow-circle-down' |
  'default-arrow-circle-left' |
  'default-arrow-circle-right' |
  'default-arrow-circle-up' |
  'default-arrow-head-down' |
  'default-arrow-head-left' |
  'default-arrow-head-right' |
  'default-arrow-head-up' |
  'default-arrow-move-horizontal-axis' |
  'default-arrow-move-vertical-axis' |
  'default-arrow-simple-down' |
  'default-arrow-simple-left' |
  'default-arrow-simple-long-right' |
  'default-arrow-simple-right' |
  'default-arrow-simple-up' |
  'default-arrow-switch' |
  'default-arrow-turn-left' |
  'default-arrow-turn-right' |
  'default-arrow-up-down-left-right' |
  'default-arrow-up-down' |
  'default-avatar-multiple' |
  'default-avatar-single' |
  'default-award-medal' |
  'default-award-trophy' |
  'default-badge-alert' |
  'default-badge-blocked' |
  'default-badge-error' |
  'default-badge-help' |
  'default-badge-info' |
  'default-badge-warning' |
  'default-basic-checkmark-block' |
  'default-basic-checkmark-circle' |
  'default-basic-checkmark-line' |
  'default-basic-checkmark-wide-block' |
  'default-basic-checkmark-wide' |
  'default-basic-minus-block' |
  'default-basic-minus-circle' |
  'default-basic-minus-line' |
  'default-basic-minus-wide' |
  'default-basic-plus-block' |
  'default-basic-plus-circle' |
  'default-basic-plus-line' |
  'default-basic-plus-wide' |
  'default-basic-shape-circle-filled' |
  'default-basic-shape-circle' |
  'default-basic-shape-heart' |
  'default-basic-shape-square' |
  'default-basic-shape-star-half' |
  'default-basic-shape-star' |
  'default-basic-shape-triangle' |
  'default-basic-stack-block' |
  'default-basic-stack-circle' |
  'default-basic-stack-line' |
  'default-basic-x-block' |
  'default-basic-x-circle' |
  'default-basic-x-line' |
  'default-basic-x-wide' |
  'default-bell-bell' |
  'default-bell-crossed' |
  'default-building-home' |
  'default-building-shop' |
  'default-calendar-empty' |
  'default-calendar-full' |
  'default-chart-bar-filled' |
  'default-chart-bar' |
  'default-chart-heart-puls' |
  'default-chart-line' |
  'default-chart-pie' |
  'default-chart-sales' |
  'default-communication-envelope' |
  'default-communication-forward' |
  'default-communication-inbox' |
  'default-communication-quote' |
  'default-communication-reply' |
  'default-communication-speech-bubble' |
  'default-communication-speech-bubbles' |
  'default-device-dashboard' |
  'default-device-database' |
  'default-device-desktop' |
  'default-device-gamecontroler' |
  'default-device-harddisk' |
  'default-device-headset' |
  'default-device-keyboard' |
  'default-device-laptop' |
  'default-device-micophone' |
  'default-device-mobile' |
  'default-device-photocamera' |
  'default-device-printer' |
  'default-device-server' |
  'default-device-tablet' |
  'default-device-video-camera' |
  'default-documentation-file' |
  'default-documentation-map-closed' |
  'default-documentation-map-open' |
  'default-documentation-paper-pencil-signed' |
  'default-documentation-paper-pencil' |
  'default-documentation-paperclip' |
  'default-documentation-pushpin' |
  'default-eye-crossed' |
  'default-eye-open' |
  'default-folder-thumbnail' |
  'default-location-flag' |
  'default-location-gps' |
  'default-location-map' |
  'default-location-marker' |
  'default-lock-closed' |
  'default-lock-fingerprint' |
  'default-lock-key' |
  'default-lock-open' |
  'default-money-card' |
  'default-money-cash' |
  'default-money-wallet' |
  'default-object-address' |
  'default-object-beer' |
  'default-object-books' |
  'default-object-briefcase' |
  'default-object-globe' |
  'default-object-graduate-cap' |
  'default-object-image' |
  'default-object-lab-flask' |
  'default-object-lightbulb' |
  'default-object-marketing' |
  'default-object-paint' |
  'default-object-paperplane' |
  'default-object-pawn' |
  'default-object-plug' |
  'default-object-puzzle-piece' |
  'default-object-rocket' |
  'default-object-scale' |
  'default-object-shield-full' |
  'default-object-shield' |
  'default-object-sofa' |
  'default-object-traffic-pawn' |
  'default-os-browser' |
  'default-os-layers' |
  'default-os-terminal' |
  'default-package-closed' |
  'default-package-gift' |
  'default-package-open' |
  'default-review-star-full' |
  'default-review-star-half' |
  'default-shopping-basket' |
  'default-shopping-cart' |
  'default-shopping-paper-bag-product' |
  'default-shopping-paper-bag' |
  'default-shopping-plastic-bag' |
  'default-sidebar-align-left' |
  'default-sidebar-align-right' |
  'default-sidebar-close' |
  'default-sidebar-open' |
  'default-symbol-content' |
  'default-symbol-euro' |
  'default-symbol-flow' |
  'default-symbol-infinity' |
  'default-symbol-products' |
  'default-symbol-rule' |
  'default-target-big' |
  'default-target-with-block' |
  'default-text-align-center' |
  'default-text-align-justify' |
  'default-text-align-left' |
  'default-text-align-right' |
  'default-text-code' |
  'default-text-editor-align-left' |
  'default-text-editor-align-right' |
  'default-text-editor-bold' |
  'default-text-editor-code' |
  'default-text-editor-expand' |
  'default-text-editor-italic' |
  'default-text-editor-link' |
  'default-text-editor-list-numberd' |
  'default-text-editor-list-unordered' |
  'default-text-editor-list' |
  'default-text-editor-media' |
  'default-text-editor-re-undo' |
  'default-text-editor-redo' |
  'default-text-editor-shrink' |
  'default-text-editor-strikethrough' |
  'default-text-editor-style' |
  'default-text-editor-subscript' |
  'default-text-editor-superscript' |
  'default-text-editor-table-delete-column' |
  'default-text-editor-table-delete-row' |
  'default-text-editor-table-insert-column-after' |
  'default-text-editor-table-insert-column-before' |
  'default-text-editor-table-insert-row-after' |
  'default-text-editor-table-insert-row-before' |
  'default-text-editor-table' |
  'default-text-editor-underline' |
  'default-text-editor-undo' |
  'default-text-editor-variables' |
  'default-text-emoji' |
  'default-text-list' |
  'default-text-style-bold' |
  'default-text-style-italic' |
  'default-text-style-underline' |
  'default-text-table' |
  'default-time-clock' |
  'default-time-hourglass' |
  'default-tools-colorpicker' |
  'default-tools-pencil-brush' |
  'default-tools-ruler-pencil' |
  'default-tools-tools' |
  'default-view-compact' |
  'default-view-grid' |
  'default-view-normal' |
  'default-view-split' |
  'default-web-bug' |
  'default-web-dashboard' |
  'default-web-layout' |
  'default-web-link' |
  'default-web-loading-circle' |
  'default-web-loading-star' |
  'default-web-variants' |
  'multicolor-action-play' |
  'multicolor-file-thumbnail-broken' |
  'multicolor-file-thumbnail-csv' |
  'multicolor-file-thumbnail-doc' |
  'multicolor-file-thumbnail-jpg' |
  'multicolor-file-thumbnail-mov' |
  'multicolor-file-thumbnail-normal' |
  'multicolor-file-thumbnail-pdf' |
  'multicolor-file-thumbnail-ppt' |
  'multicolor-file-thumbnail-svg' |
  'multicolor-file-thumbnail-txt' |
  'multicolor-file-thumbnail-xls' |
  'multicolor-file-type-doc' |
  'multicolor-file-type-media' |
  'multicolor-file-type-pdf' |
  'multicolor-file-type-tabledata' |
  'multicolor-file-type-text' |
  'multicolor-folder-breadcrumbs-back-to-root' |
  'multicolor-folder-breadcrumbs-dropdown' |
  'multicolor-folder-breadcrumbs' |
  'multicolor-folder-thumbnail--green' |
  'multicolor-folder-thumbnail--grey' |
  'multicolor-folder-thumbnail--pink' |
  'muAicolor-folder-thumbnail--purple' |
  'multicolor-folder-thumbnail-back' |
  'multicolor-folder-thumbnail' |
  'multicolor-folder-tree-open' |
  'multicolor-folder-tree' |
  'small-arrow-360-left' |
  'small-arrow-360-right' |
  'small-arrow-double-small-double-right' |
  'small-arrow-large-double-down' |
  'small-arrow-large-double-left' |
  'small-arrow-large-double-right' |
  'small-arrow-large-double-top' |
  'small-arrow-large-down' |
  'small-arrow-large-left' |
  'small-arrow-large-right' |
  'small-arrow-large-up' |
  'small-arrow-medium-double-left' |
  'small-arrow-medium-double-right' |
  'small-arrow-medium-down' |
  'small-arrow-medium-left' |
  'small-arrow-medium-right' |
  'small-arrow-medium-up' |
  'small-arrow-next-line' |
  'small-arrow-small-double-down' |
  'small-arrow-small-double-left' |
  'small-arrow-small-double-right' |
  'small-arrow-small-double-up' |
  'small-arrow-small-down-line' |
  'small-arrow-small-down' |
  'small-arrow-small-external' |
  'small-arrow-small-left' |
  'small-arrow-small-reoder' |
  'small-arrow-small-right' |
  'small-arrow-small-up' |
  'small-copy' |
  'small-default-checkmark-circle' |
  'small-default-checkmark-line-large' |
  'small-default-checkmark-line-medium' |
  'small-default-checkmark-line-small' |
  'small-default-checkmark-square' |
  'small-default-circle-large' |
  'small-default-circle-medium' |
  'small-default-circle-small' |
  'small-default-circle-x-small' |
  'small-default-heart' |
  'small-default-minus-circle' |
  'small-default-minus-large' |
  'small-default-minus-medium' |
  'small-default-minus-small' |
  'small-default-minus-square' |
  'small-default-plus-circle' |
  'small-default-plus-line-large' |
  'small-default-plus-line-medium' |
  'small-default-plus-line-small' |
  'small-default-plus-square' |
  'small-default-rule' |
  'small-default-square' |
  'small-default-stack-circle' |
  'small-default-stack-filter' |
  'small-default-stack-line' |
  'small-default-stack-line2' |
  'small-default-stack-square' |
  'small-default-textwrap' |
  'small-default-x-circle' |
  'small-default-x-drag-horizontal' |
  'small-default-x-drag-vertical' |
  'small-default-x-line-large' |
  'small-default-x-line-medium' |
  'small-default-x-line-small' |
  'small-default-x-square' |
  'small-exclamationmark' |
  'small-eye' |
  'small-help' |
  'small-image' |
  'small-lock-closed' |
  'small-lock-collapse' |
  'small-lock-expand' |
  'small-lock-h-collapse' |
  'small-lock-h-expand' |
  'small-lock-open' |
  'small-more' |
  'small-pencil-paper' |
  'small-pencil' |
  'small-printer' |
  'small-questionmark' |
  'small-search' |
  'small-settings' |
  'small-thumb-down' |
  'small-thumb-up' |
  'small-trash' |
  'small-traslated' |
  'small-trending-down' |
  'small-trending-up' |
  'solid-clock' |
  'text-editor-undo';
